export const EMAILS_INJECTION_TOKENS = {
  EMAIL_PROVIDER: 'EMAIL_PROVIDER',
  TEMPLATE_ENGINE: 'TEMPLATE_ENGINE',
  TEMPLATE_REPOSITORY: 'TEMPLATE_REPOSITORY',
} as const;

export type EMailsInjectionTokens =
  (typeof EMAILS_INJECTION_TOKENS)[keyof typeof EMAILS_INJECTION_TOKENS];
